services:
  - type: web
    name: consulta-toa
    env: python
    plan: free
    buildCommand: bash render-build.sh
    startCommand: gunicorn api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
